#!/bin/bash

if [ "$EUID" == 0 ]; then

    DEBIAN_FRONTEND=noninteractive apt -yq install acl attr samba samba-dsdb-modules samba-vfs-modules winbind libpam-winbind libnss-winbind libpam-krb5 krb5-config krb5-user dnsutils
    rm /etc/samba/smb.conf

    while [ -z "${KerberosRealm}" ]; do
	if [ -z "${KRBI}" ]; then
	    KRBI=1
	elif [ "${KRBI}" ]; then
	    echo "Kerberos realm must be filled"
	fi
	read -p "Enter Kerberos realm:" KerberosRealm
    done

    while [ -z "${DomainName}" ]; do
	if [ -z "${DNI}" ]; then
	    DNI=1
	elif [ "${DNI}" ]; then
	    echo "Domain name must be filled"
	fi
	read -p "Enter domain name:" DomainName
    done

    while [ -z "${AdminPass}" ]; do
	if [ -z "${ADPI}" ]; then
	    ADPI=1
	elif [ "${ADPI}" ]; then
	    echo "Admin password must be filled"
	fi
	read -p "Enter domain administrator password:" AdminPass
    done

    samba-tool domain provision --server-role=dc --use-rfc2307 --dns-backend=SAMBA_INTERNAL --realm="${KerberosRealm}" --domain="${DomainName}" --adminpass="${AdminPass}"
    cp /var/lib/samba/private/krb5.conf /etc/krb5.conf

    pkill smbd
    pkill winbindd
    pkill nmbd

    samba
else
    echo "Script must be started as root"
fi

exit 0